import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sharing Session</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Link href='/Demo1'>Demo 01 (Value vs Reference types)</Link>
        <br />
        <Link href='/Demo2'>Demo 02 (Memo part 1)</Link>
        
        <Link href='/Demo7'>Demo 07 (Nested Object Problem)</Link>
        <Link href='/Demo8'>Demo 07 (Nested Object Improvement I)</Link>
        <Link href='/Demo9'>Demo 07 (Nested Object Improvement II)</Link>
        <br />
      </main>
    </div>
  );
}
